// Code generated by mockery v2.10.4. DO NOT EDIT.

package cryptomocks

import (
	cryptoutil "medichat-be/cryptoutil"

	mock "github.com/stretchr/testify/mock"
)

// JWTProvider is an autogenerated mock type for the JWTProvider type
type JWTProvider struct {
	mock.Mock
}

// CreateToken provides a mock function with given fields: userID
func (_m *JWTProvider) CreateToken(userID int64) (string, error) {
	ret := _m.Called(userID)

	var r0 string
	if rf, ok := ret.Get(0).(func(int64) string); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyToken provides a mock function with given fields: token
func (_m *JWTProvider) VerifyToken(token string) (cryptoutil.JWTClaims, error) {
	ret := _m.Called(token)

	var r0 cryptoutil.JWTClaims
	if rf, ok := ret.Get(0).(func(string) cryptoutil.JWTClaims); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(cryptoutil.JWTClaims)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
